# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2426f884bff71b1c7154e34ee8d0a6436d996b91953da6e65c8baac701a52464ead6c3e03dd90debfe8cd380c1eff79adb5b7c586123d97a178c142f356cd3d8

test:
  secret_key_base: 9661e6b29b7cbc5d5e9e5c3dee50a399fef026951d36e6b0e93ed974f6455004eaaab702064e00d34abb1f6bdada86dfaab520af9310a2aec02af6e503ae6baf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
